README.md

+ typo fixes
+ mention of running composer install

updated README to include development information for theme development

---

ansible/deploy.yml
ansible/deploy.yml.README.md
ansible/hosts_environments
ansible/tasks/after-symlink-tasks.yml

ansistrano initial commit

---

ansible/deploy.yml

ansistrano: add composer step for each theme. (temp workaround)

---

composer.json
config/language/es/block.block.drupalcampblockforlandingaboutsponsoring.yml
config/language/es/mailchimp_signup.mailchimp_signup.dcamp_mailchimp.yml
web/modules/custom/dcamp/dcamp.install
web/themes/dcamp_2017_landing_theme/templates/page.html.twig

For https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/42

[#42] Various homepage adjustments

---

config/block.block.drupalcampblockforlandingaboutsponsoring.yml
web/modules/custom/dcamp/dcamp.install

There was a typo in the contact. Details at
https://trello.com/c/JXDImsFy/19-cambiar-datos-de-contacto-del-dossier#comment-589d4553507c0242d5990e01

Fix the sponsor prospectus URL

---

composer.json
composer.lock

update composer.json plus updates d8 version

---

config/system.performance.yml

Page cache to 5 minutes.
JS and CSS aggregation.

[#54] Set caching and aggregation

---

web/themes/dcamp_2017_theme/templates/frontpage.html.twig

[#66] Fix the homepage slogan

---

ansible/deploy.yml
ansible/tasks/after-symlink-tasks.yml

Fix #54 . Variable added to Jenkins jobs

ansistrano: add varnish cleanup step. Fix #54

---

config/core.entity_form_display.node.speaker.default.yml
config/core.entity_view_display.node.speaker.default.yml
config/core.entity_view_display.node.speaker.full.yml
config/core.entity_view_display.node.speaker.teaser.yml
config/field.field.node.speaker.field_linkedin.yml
config/field.storage.node.field_linkedin.yml
config/views.view.featured_speakers.yml
web/modules/custom/dcamp/dcamp.install
web/themes/dcamp_2017_theme/templates/content/node--speaker--full.html.twig

@nuez, @ckrina, feel free to take over this PR and add the theming for the teaser, or just merge it and create a new PR for it.

[#83] Add LinkedIn field and remove full_name

---

composer.json
composer.lock
config/core.entity_view_mode.block.token.yml
config/core.entity_view_mode.block_content.token.yml
config/core.entity_view_mode.comment.token.yml
config/core.entity_view_mode.contact_message.token.yml
config/core.entity_view_mode.file.token.yml
config/core.entity_view_mode.menu_link_content.token.yml
config/core.entity_view_mode.node.token.yml
config/core.entity_view_mode.shortcut.token.yml
config/core.entity_view_mode.taxonomy_term.token.yml
config/core.entity_view_mode.tour.token.yml
config/core.entity_view_mode.user.token.yml
config/core.extension.yml
config/language.content_settings.redirect.redirect.yml
config/pathauto.pattern.news.yml
config/pathauto.pattern.pages.yml
config/pathauto.pattern.speakers.yml
config/pathauto.settings.yml
config/redirect.settings.yml
config/system.action.pathauto_update_alias_node.yml
config/system.action.pathauto_update_alias_user.yml
config/system.action.redirect_delete_action.yml
config/views.view.redirect.yml
web/modules/custom/dcamp/dcamp.install

Plus add aliases to feature speakers

Install and configure Pathauto and Redirect

---

README.md
docker-compose.yml
docker-lamp/.gitignore
docker-lamp/LICENSE
docker-lamp/README.md
docker-lamp/config/mysql/my.cnf
docker-lamp/config/mysql/my.cnf.orig
docker-lamp/config/php/5.6/php.ini
docker-lamp/config/php/5.6/php.ini-development
docker-lamp/config/php/5.6/php.ini-production
docker-lamp/config/php/7.0/php.ini
docker-lamp/config/php/7.0/php.ini-development
docker-lamp/config/php/7.0/php.ini-production
docker-lamp/config/php/opcache-recommended.ini
docker-lamp/config/php/xdebug.ini
docker-lamp/config/vhosts/010-app.conf
docker-lamp/config/vhosts/011-app-ssl.conf
docker-lamp/data/database/.gitignore
docker-lamp/local-docker.sh

I added a docker environment to facilitate new users to set up the environment with docker containers

Docker environment

---

web/modules/custom/dcamp/dcamp.install
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.body.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_bitbucket.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_company.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_drupal_org.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_facebook.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_github.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_linkedin.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_photo.yml
web/modules/custom/dcamp_speakers/config/install/field.field.node.speaker.field_twitter.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_bitbucket.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_company.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_drupal_org.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_facebook.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_github.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_linkedin.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_photo.yml
web/modules/custom/dcamp_speakers/config/install/field.storage.node.field_twitter.yml
web/modules/custom/dcamp_speakers/config/install/node.type.speaker.yml
web/modules/custom/dcamp_speakers/dcamp_speakers.info.yml
web/themes/dcamp_2017_theme/templates/frontpage.html.twig

For https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/100

100 speaker adjustments

---

config/language.content_settings.node.page.yml
config/node.type.page.yml

We need it to translate the Survival Guide.

116: Basic page now is a translatable content.

---

config/core.base_field_override.node.speaker.changed.yml
config/core.base_field_override.node.speaker.created.yml
config/core.base_field_override.node.speaker.menu_link.yml
config/core.base_field_override.node.speaker.path.yml
config/core.base_field_override.node.speaker.promote.yml
config/core.base_field_override.node.speaker.status.yml
config/core.base_field_override.node.speaker.sticky.yml
config/core.base_field_override.node.speaker.uid.yml
config/field.field.node.speaker.body.yml
config/language.content_settings.node.speaker.yml
config/language/es/views.view.block_content.yml
config/language/es/views.view.content.yml
config/language/es/views.view.files.yml
config/language/es/views.view.frontpage.yml
config/language/es/views.view.user_admin_people.yml

Exported this config from production so I could translate
Cristina's bio.

Translate speaker content type

---

web/themes/dcamp_2017_theme/templates/menu--main.html.twig

Translate menu aside and remove Buy Tickets

---

config/core.extension.yml

Otherwise drush cim sync uninstalls it

[COLDFIX] :icecream: Export config to keep dcamp_sessions installed

---

ansible/tasks/after-symlink-tasks.yml

ansistrano: Add debug information for drush commands

---

composer.json
composer.lock
config/core.entity_form_display.node.page.default.yml
config/core.extension.yml
web/modules/custom/dcamp/dcamp.install
web/modules/custom/dcamp_api/dcamp_api.info.yml
web/modules/custom/dcamp_sessions/dcamp_sessions.routing.yml
web/modules/custom/dcamp_sessions/src/Controller/DcampSessionsController.php

Pages: http://dcamp.local/jsonapi/node/page
Sponsors: http://dcamp.local/jsonapi/node/sponsor
Speakers: http://dcamp.local/jsonapi/node/speaker
Sessions: http://dcamp.local/sessions/proposed?format=json

[#133] Expose content via JSON API

---

web/modules/custom/dcamp_sessions/src/Controller/DcampSessionsController.php

#160 this field is not public it's a drupalcamp organizer comment. I prefer remove from view.

#160 Remove Extra field in session view.

---

config/field.storage.node.field_sponsor_type.yml

#177 Created bronze sponsor type.

---

web/modules/custom/dcamp_attendees/dcamp_attendees.module
web/modules/custom/dcamp_attendees/src/Entity/Attendee.php
web/themes/dcamp_2017_theme/dcamp_2017_theme.theme

If it is not an image URL, show the default headshot

Validate headshot URLs

---

web/modules/custom/dcamp_sessions/src/Controller/DcampSessionsController.php

Should be enough to avoid duplicates.

Fix session aliases by appending the twitter handle

---

web/themes/dcamp_2017_theme/templates/html.html.twig

adjust mobile theme color

---

web/modules/custom/dcamp_attendees/src/EventBriteService.php

Fixes https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/223

[#223] Filter out cancelled tickets

---

config/core.base_field_override.menu_link_content.menu_link_content.changed.yml
config/core.base_field_override.menu_link_content.menu_link_content.description.yml
config/core.base_field_override.menu_link_content.menu_link_content.title.yml
config/field.field.node.article.field_image.yml
config/field.field.user.user.user_picture.yml
config/language.content_settings.menu_link_content.menu_link_content.yml
config/language/es/tour.tour.views-ui.yml
config/language/es/views.view.content.yml
config/language/es/views.view.frontpage.yml
config/language/es/views.view.user_admin_people.yml
config/pathauto.pattern.news.yml
config/pathauto.pattern.pages.yml
config/pathauto.pattern.speakers.yml

After adding a few translations

Export config from production

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig

#244  Fixed this points:
- Add the Juan Olalla session (I forgot it, but we have a free slot for him)
- Add a td class with the session level.
- Add a td class in the lighting sessions
Extra ball:
- Fixed Saturday lunch break. It was only of 1h.

#244 schedule improvement

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig

Some sessions order has been changed.

[#255] Change some session orders.

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig
web/modules/custom/dcamp_sessions/src/Controller/DcampSessionsController.php

- Added Victor' session to the schedule
- Added Victor' session to the selected sessions array
- Linked the assembly slot to the Assembly description node.

[#259]:  Added Victor session and adjust Salva's

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig
web/modules/custom/dcamp_sessions/src/Controller/DcampSessionsController.php

#263 Added JJM session to the schedule.

---

web/themes/dcamp_2017_theme/templates/frontpage.html.twig

[#261] Repurpose tickets cta for promoting the schedule

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig
web/modules/custom/dcamp_sessions/src/SessionProposalsService.php

#275 schedule changes

---

README.md
composer.lock
web/.eslintrc.json
web/.gitattributes

281 update core

---

web/themes/dcamp_2017_theme/templates/frontpage.html.twig
web/themes/dcamp_2017_theme/templates/page.html.twig

* Remove Buy tickets.
* Change slogan to Thank you!
* Reword the shedule call to action so it links to photos and videos.

[#282] Adjust homepage after the event

---

README.md

Fix link to docker-lamp

---

config/block.block.drupalcampblockforlandingaboutevent_2018.yml
config/block.block.drupalcampblockforlandingaboutsponsoring_2.yml
config/block.block.drupalcampblockforlandingaboutthecommunity_2018.yml
config/block.block.drupalcampblockforlandingaboutthelocation_2018.yml
config/block.block.drupalcampblockforlandingforstayingupdated_2018.yml
config/language/es/block.block.drupalcampblockforlandingaboutevent_2018.yml
config/language/es/block.block.drupalcampblockforlandingaboutsponsoring_2.yml
config/language/es/block.block.drupalcampblockforlandingaboutthecommunity_2018.yml
config/language/es/block.block.drupalcampblockforlandingforstayingupdated_2018.yml

Here is the English version:
And here is the Spanish one:
Apart from a few design touches, I think that we are ready to go.

[#293] Configure and translate landing blocks

---

composer.json
composer.lock

Updates to the latest security release.

Update core to 8.3.7

---

web/modules/custom/dcamp_attendees/dcamp_attendees.install
web/modules/custom/dcamp_attendees/fixtures/attendees.json
web/modules/custom/dcamp_attendees/src/Entity/Attendee.php
web/modules/custom/dcamp_attendees/src/EventBriteService.php
web/themes/dcamp_2018_theme/styles/main.css
web/themes/dcamp_2018_theme/templates/frontpage.html.twig

Add Tickets block and adjust ticket and question identifiers

---

web/modules/custom/dcamp_attendees/templates/attendees-list.html.twig

Add a buy tickets block at the attendees listing

---

composer.json
composer.lock
web/modules/custom/dcamp_sessions/dcamp_sessions.install
web/modules/custom/dcamp_sessions/src/SessionProposalsService.php
web/sites/default/tugboat.settings.php
web/themes/dcamp_2018_theme/templates/frontpage.html.twig

Hi, @juampynr !
I don't have the site installed but with this PR the session selected should works.  The `getSelected` method should works only with the array keys (without any other data)  but I cannot test wihtout install the site. 
If you have to edit something, be free :-)

Added list of selected sessions.

---

config/core.extension.yml
web/modules/custom/dcamp_schedule/dcamp_schedule.install
web/modules/custom/dcamp_schedule/templates/schedule.html.twig

- Disabled Accepted sessions menu item
- Enabled Schedule menu item
- Updated schedule template with the 2018 sessions.

Added 2018 schedule

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig

Bugs commented here:
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/337

Fixed all bugs in schedule.

---

web/modules/custom/dcamp_schedule/templates/schedule.html.twig

(ya está aquí el pesado de rvilar)

Un ya típico cambio en toda DrupalCamp

---

web/themes/coming_soon_th/templates/layout/page-en.html.twig

Solves the typos found at the EN version of the homepage.

Fix typos found at the EN version of the homepage.

---

web/themes/coming_soon_th/templates/layout/page-en.html.twig
web/themes/coming_soon_th/templates/layout/page-es.html.twig

Cambios necesarios para reflejar la suspension del evento
